/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import java.text.NumberFormat;
import java.util.Enumeration;
import java.util.HashMap;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;

import vendingMachine.Product;
import vendingMachine.VendingMachineController;

/**
 *
 * @author Jack
 */
public class VendingMachineGUI extends javax.swing.JFrame {

	private VendingMachineController controller;
	
	private HashMap<ButtonModel, Product> buttonProduct;
	
	public static final String PLACEHOLDER = "Insert Credit...";
	public static final String CARD_LOGIN_MESSAGE = "Account linked";
	
	/*
	 * The code below was researched at the following resource:
	 * 
	 * daiscog, 2015. Java Currency Number format. [Online] 
	 * Available at: https://stackoverflow.com/questions/2379221/java-currency-number-format
	 * [Accessed 7 December 2021].
	 * 
	 * The resource was used to find how to format an int into a currency
	 * format. The code has been adapted to suit this specific application
	 * and is not a direct copy
	 */
	private final NumberFormat moneyFormatter = NumberFormat.getCurrencyInstance();
	
    /**
     * Creates new form VendingMachineGUI
     */
    public VendingMachineGUI(VendingMachineController controller) {
        this.controller = controller;
    	initComponents();
    	updatePrices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productSelector = new ButtonGroup();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        contentPanel = new JPanel();
        outputPanel = new JPanel();
        output = new JLabel();
        selectionPanel = new JPanel();
        cokePanel = new JPanel();
        cokeButton = new JToggleButton();
        cokeLabelPanel = new JPanel();
        cokeLabel = new JLabel();
        cokePrice = new JLabel();
        lemonadePanel = new JPanel();
        lemonadeButton = new JToggleButton();
        lemonadeLabelPanel = new JPanel();
        lemonadeLabel = new JLabel();
        lemonadePrice = new JLabel();
        tangoPanel = new JPanel();
        tangoButton = new JToggleButton();
        tangoLabelPanel = new JPanel();
        tangoLabel = new JLabel();
        tangoPrice = new JLabel();
        waterPanel = new JPanel();
        waterButton = new JToggleButton();
        waterLabelPanel = new JPanel();
        waterLabel = new JLabel();
        waterPrice = new JLabel();
        pepsiPanel = new JPanel();
        pepsiButton = new JToggleButton();
        pepsiLabelPanel = new JPanel();
        pepsiLabel = new JLabel();
        pepsiPrice = new JLabel();
        spritePanel = new JPanel();
        spriteButton = new JToggleButton();
        spriteLabelPanel = new JPanel();
        spriteLabel = new JLabel();
        spritePrice = new JLabel();
        jPanel3 = new JPanel();
        purchaseButton = new JButton();
        clearButton = new JButton();
        cancelButton = new JButton();
        buttonProduct = new HashMap<ButtonModel, Product>();

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edge Hill Vender");

        jLabel1.setFont(new java.awt.Font("Kefa", 0, 48)); // NOI18N
        jLabel1.setText("Edge Hill Café");
        jLabel1.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 10));
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        contentPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contentPanel.setLayout(new BorderLayout());

        outputPanel.setLayout(new BorderLayout());

        output.setFont(new java.awt.Font("Silom", 0, 36)); // NOI18N
        output.setHorizontalAlignment(SwingConstants.CENTER);
        output.setText(PLACEHOLDER);
        output.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(10, 10, 20, 10), BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), new java.awt.Color(102, 0, 102))));
        outputPanel.add(output, BorderLayout.CENTER);

        contentPanel.add(outputPanel, BorderLayout.NORTH);

        selectionPanel.setBorder(BorderFactory.createTitledBorder("Select a product"));
        selectionPanel.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        cokePanel.setLayout(new BorderLayout());

        productSelector.add(cokeButton);
        cokeButton.setIcon(new ImageIcon("assets/coke.png"));
        cokeButton.setEnabled(false);
        cokePanel.add(cokeButton, BorderLayout.CENTER);

        cokeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        cokeLabel.setText("Coke -");
        cokeLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        cokeLabelPanel.add(cokeLabel);

        cokeLabelPanel.add(cokePrice);

        cokePanel.add(cokeLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(cokePanel);

        lemonadePanel.setLayout(new BorderLayout());

        productSelector.add(lemonadeButton);
        lemonadeButton.setIcon(new ImageIcon("assets/lemonade.png"));
        lemonadeButton.setEnabled(false);
        lemonadePanel.add(lemonadeButton, BorderLayout.CENTER);

        lemonadeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lemonadeLabel.setText("Lemonade -");
        lemonadeLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        lemonadeLabelPanel.add(lemonadeLabel);

        lemonadeLabelPanel.add(lemonadePrice);

        lemonadePanel.add(lemonadeLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(lemonadePanel);

        tangoPanel.setLayout(new BorderLayout());

        productSelector.add(tangoButton);
        tangoButton.setIcon(new ImageIcon("assets/tango.png"));
        tangoButton.setEnabled(false);
        tangoPanel.add(tangoButton, BorderLayout.CENTER);

        tangoLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tangoLabel.setText("Tango -");
        tangoLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        tangoLabelPanel.add(tangoLabel);

        tangoLabelPanel.add(tangoPrice);

        tangoPanel.add(tangoLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(tangoPanel);

        waterPanel.setLayout(new BorderLayout());

        productSelector.add(waterButton);
        waterButton.setIcon(new ImageIcon("assets/water.png"));
        waterButton.setEnabled(false);
        waterPanel.add(waterButton, BorderLayout.CENTER);

        waterLabel.setHorizontalAlignment(SwingConstants.CENTER);
        waterLabel.setText("Water -");
        waterLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        waterLabelPanel.add(waterLabel);

        waterLabelPanel.add(waterPrice);

        waterPanel.add(waterLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(waterPanel);

        pepsiPanel.setLayout(new BorderLayout());

        productSelector.add(pepsiButton);
        pepsiButton.setIcon(new ImageIcon("assets/pepsi.png"));
        pepsiButton.setEnabled(false);
        pepsiPanel.add(pepsiButton, BorderLayout.CENTER);

        pepsiLabel.setHorizontalAlignment(SwingConstants.CENTER);
        pepsiLabel.setText("Pepsi -");
        pepsiLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        pepsiLabelPanel.add(pepsiLabel);

        pepsiLabelPanel.add(pepsiPrice);

        pepsiPanel.add(pepsiLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(pepsiPanel);

        spritePanel.setLayout(new BorderLayout());

        productSelector.add(spriteButton);
        spriteButton.setIcon(new ImageIcon("assets/sprite.png"));
        spriteButton.setEnabled(false);
        spritePanel.add(spriteButton, BorderLayout.CENTER);

        spriteLabel.setHorizontalAlignment(SwingConstants.CENTER);
        spriteLabel.setText("Sprite -");
        spriteLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        spriteLabelPanel.add(spriteLabel);

        spriteLabelPanel.add(spritePrice);

        spritePanel.add(spriteLabelPanel, BorderLayout.SOUTH);

        selectionPanel.add(spritePanel);

        contentPanel.add(selectionPanel, BorderLayout.CENTER);
        selectionPanel.getAccessibleContext().setAccessibleDescription("");

        purchaseButton.setText("Purchase");
        purchaseButton.addActionListener(controller);
        jPanel3.add(purchaseButton);

        clearButton.setText("Clear");
        clearButton.addActionListener(controller);
        jPanel3.add(clearButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(controller);
        jPanel3.add(cancelButton);

        contentPanel.add(jPanel3, BorderLayout.PAGE_END);

        getContentPane().add(contentPanel, BorderLayout.CENTER);

        pack();
        
        buttonProduct.put(cokeButton.getModel(), Product.COKE);
        buttonProduct.put(lemonadeButton.getModel(), Product.LEMONADE);
        buttonProduct.put(tangoButton.getModel(), Product.TANGO);
        buttonProduct.put(waterButton.getModel(), Product.WATER);
        buttonProduct.put(pepsiButton.getModel(), Product.PEPSI);
        buttonProduct.put(spriteButton.getModel(), Product.SPRITE);
    }// </editor-fold>//GEN-END:initComponents
    
    public void updatePrices() {
		
		cokePrice.setText(moneyFormatter.format(controller.getPrice(Product.COKE)));
		lemonadePrice.setText(moneyFormatter.format(controller.getPrice(Product.LEMONADE)));
		tangoPrice.setText(moneyFormatter.format(controller.getPrice(Product.TANGO)));
		waterPrice.setText(moneyFormatter.format(controller.getPrice(Product.WATER)));
		pepsiPrice.setText(moneyFormatter.format(controller.getPrice(Product.PEPSI)));
		spritePrice.setText(moneyFormatter.format(controller.getPrice(Product.SPRITE)));
    
    }
    
    public String formatCurrency(double amount) {
    	return moneyFormatter.format(amount);
    }
    
    public void clearSelection() {
    	productSelector.clearSelection();
    }
    
    public JLabel getOutput() {
    	return output;
    }
    
    public Product getSelectedProduct() {
    	return buttonProduct.get(productSelector.getSelection());
    }

    public void setSelectorEnabled(boolean enabled) {
    	Enumeration<AbstractButton> e = productSelector.getElements();
    	while(e.hasMoreElements()) {
    		e.nextElement().setEnabled(enabled);
   		}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JButton clearButton;
    private JToggleButton cokeButton;
    private JLabel cokeLabel;
    private JPanel cokeLabelPanel;
    private JPanel cokePanel;
    private JLabel cokePrice;
    private JPanel contentPanel;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JToggleButton lemonadeButton;
    private JLabel lemonadeLabel;
    private JPanel lemonadeLabelPanel;
    private JPanel lemonadePanel;
    private JLabel lemonadePrice;
    private JLabel output;
    private JPanel outputPanel;
    private JToggleButton pepsiButton;
    private JLabel pepsiLabel;
    private JPanel pepsiLabelPanel;
    private JPanel pepsiPanel;
    private JLabel pepsiPrice;
    private ButtonGroup productSelector;
    private JButton purchaseButton;
    private JPanel selectionPanel;
    private JToggleButton spriteButton;
    private JLabel spriteLabel;
    private JPanel spriteLabelPanel;
    private JPanel spritePanel;
    private JLabel spritePrice;
    private JToggleButton tangoButton;
    private JLabel tangoLabel;
    private JPanel tangoLabelPanel;
    private JPanel tangoPanel;
    private JLabel tangoPrice;
    private JToggleButton waterButton;
    private JLabel waterLabel;
    private JPanel waterLabelPanel;
    private JPanel waterPanel;
    private JLabel waterPrice;
    // End of variables declaration//GEN-END:variables
}
